#!/opt/python3.12/bin/python3
# -*- coding: utf-8 -*-
"""
gen_catalog.py - build-time catalog generator for Local Dream ET (desktop).

models.json is the SINGLE SOURCE OF TRUTH for:
  * the model list (CPU runnable SD1.5 + locked NPU-only entries)
  * per-model trilingual descriptions / default prompt / negative prompt
  * the UI trilingual strings
  * sampler list and app version

It emits catalog.h (pure-ASCII C, all non-ASCII -> \\uXXXX) which launcher.c
#include's. The compiled EXE therefore needs NO Python at runtime; Python is
only used at build time to regenerate this header.

Usage:
  /opt/python3.12/bin/python3 tools/gen_catalog.py
Re-run after editing models.json, then rebuild launcher.c.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "models.json")
OUT = os.path.join(ROOT, "catalog.h")


def c_w(s: str) -> str:
    """Return a C wide string literal body (without the outer quotes),
    pure ASCII: backslash/quote/newline escaped, non-ASCII as \\uXXXX."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o > 0x7E:
            if o <= 0xFFFF:
                out.append("\\u%04x" % o)
            else:
                out.append("\\U%08x" % o)
        else:
            out.append(ch)
    return "".join(out)


def L(s: str) -> str:
    return 'L"' + c_w(s) + '"'


def main() -> int:
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)

    app = data["app"]
    lock = data["lock_reason"]
    ui = data["ui"]
    samplers = data["samplers"]
    models = data["models"]

    n_cpu = sum(1 for m in models if m["tab"] == "cpu")
    n_npu = sum(1 for m in models if m["tab"] == "npu")
    n_locked = sum(1 for m in models if m.get("locked"))

    lines = []
    A = lines.append
    A("/* AUTO-GENERATED by tools/gen_catalog.py from models.json -- DO NOT EDIT.")
    A(" * Re-run: /opt/python3.12/bin/python3 tools/gen_catalog.py")
    A(" * All non-ASCII is \\uXXXX escaped so the C source stays pure ASCII. */")
    A("#pragma once")
    A("")
    A('#define APP_VERSION_STR "%s"' % app["version"])
    A('#define APP_VERSION_W  L"%s"' % app["version"])
    A("#define APP_CODE       %d" % app["code"])
    A("")

    # ---- sampler display names (English, like the phone) ----
    A("static const wchar_t *g_samplers[%d] = {" % len(samplers))
    for s in samplers:
        A("    " + L(s) + ",")
    A("};")
    A("#define SAMPLER_COUNT %d" % len(samplers))
    A("")

    # aspect ratios: SD1.5 base set, DiT adds 9:16 / 16:9
    A('static const wchar_t *g_aspects_sd15[] = { L"1:1", L"3:4", L"4:3" };')
    A("#define ASPECT_SD15_COUNT 3")
    A('static const wchar_t *g_aspects_dit[] = { L"1:1", L"3:4", L"4:3", L"9:16", L"16:9" };')
    A("#define ASPECT_DIT_COUNT 5")
    A("")

    # ---- UI trilingual table ----
    # stable key order so the enum is deterministic
    keys = list(ui.keys())
    A("enum UiKey {")
    for i, k in enumerate(keys):
        A("    UIDX_%s = %d," % (k.upper(), i))
    A("    UIDX_COUNT")
    A("};")
    A("")
    A("/* g_ui[lang][key]: lang 0=zh-CN 1=en 2=zh-TW */")
    A("static const wchar_t *g_ui[3][UIDX_COUNT] = {")
    for lang in ("zh", "en", "tw"):
        A("    { /* %s */" % lang)
        for k in keys:
            A("        " + L(ui[k][lang]) + ",")
        A("    },")
    A("};")
    A("")

    # ---- model catalog ----
    A("typedef struct { const char *hf; const char *cn; const wchar_t *rel; } DlFile;")
    A("typedef struct {")
    A("    const wchar_t *id, *name;")
    A("    const wchar_t *descZh, *descEn, *descTw;")
    A("    const wchar_t *sizeZh, *sizeEn;")
    A("    const wchar_t *badge;")
    A("    const wchar_t *defPrompt, *defNeg;")
    A("    int tab;          /* 0=CPU, 1=NPU */")
    A("    int locked;       /* 1 = locked, no download/run on desktop */")
    A("    const wchar_t *lockZh, *lockEn, *lockTw;")
    A("    int nfiles;")
    A("    DlFile files[4];")
    A("} CatalogModel;")
    A("")
    A("static const CatalogModel g_models[] = {")
    for m in models:
        tab = 0 if m["tab"] == "cpu" else 1
        locked = 1 if m.get("locked") else 0
        files = m.get("files", [])
        if len(files) > 4:
            sys.stderr.write("too many files for %s\n" % m["id"])
            return 1
        A("    { /* %s */" % m["id"])
        A("        " + L(m["id"]) + ", " + L(m["name"]) + ",")
        A("        " + L(m["desc"]["zh"]) + ", " + L(m["desc"]["en"]) + ", " + L(m["desc"]["tw"]) + ",")
        A("        " + L(m["size"]["zh"]) + ", " + L(m["size"]["en"]) + ",")
        A("        " + L(m["badge"]) + ",")
        A("        " + L(m.get("prompt", "")) + ", " + L(m.get("negative", "")) + ",")
        A("        %d, %d," % (tab, locked))
        if locked:
            A("        " + L(lock["zh"]) + ", " + L(lock["en"]) + ", " + L(lock["tw"]) + ",")
        else:
            A("        L\"\", L\"\", L\"\",")
        A("        %d, {" % len(files))
        for fi in files:
            cn = fi.get("cn")
            A("            { " + ('"%s"' % fi["hf"] if fi["hf"] else "NULL") +
              ", " + (('"%s"' % cn) if cn else "NULL") +
              ", " + L(fi["rel"]) + " },")
        # pad to 4
        for _ in range(4 - len(files)):
            A("            { NULL, NULL, L\"\" },")
        A("        }")
        A("    },")
    A("};")
    A("#define MODEL_COUNT %d" % len(models))
    A("#define MODEL_CPU_COUNT %d" % n_cpu)
    A("#define MODEL_NPU_COUNT %d" % n_npu)
    A("#define MODEL_LOCKED_COUNT %d" % n_locked)
    A("")

    with open(OUT, "w", encoding="ascii") as f:
        f.write("\n".join(lines) + "\n")

    print("gen_catalog.py: wrote %s" % os.path.relpath(OUT, ROOT))
    print("  models=%d (cpu=%d, npu=%d, locked=%d), ui keys=%d, samplers=%d"
          % (len(models), n_cpu, n_npu, n_locked, len(keys), len(samplers)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
